### PR TITLE
Python 3 / waitress 0.8.10 issues

### PR DESCRIPTION
**Pull request by Doomas**
I ran into some Python 3 compatibility issues. This fix should be also compatible with Python 2.7+

Waitress 0.8.10 excepts strings instead of bytes.

### CODE REVIEW

**Comment by tilgovi** [comment]
I think you're right that this should change, but I think `latin-1` is the encoding that we should be passing, maybe.

There is a bug, but I think we want `native_(value, 'latin-1')` instead. This is what WebOb does internally, because that's what WSGI servers expect.

https://github.com/Pylons/webob/pull/150

**Comment by tilgovi** [comment]
With `text_` we get `unicode` type on Py2. With `native_` we get `str` on both, which fits PEP3333's language about unicode and what WebOb seems to have discovered is best for compatibility with servers.

**Comment by Doomas** [comment]
Yes, you're right, `native_` with `latin-1` is the correct choice.

**Comment by tilgovi** [comment]
If you could make that change, squash the commits, and force push that up to this branch I can merge this with that change. That would be excellent. Thank you!

**Comment by tilgovi** [comment]
GitHub doesn't notify me when you push commits on a PR, only when you comment. But I noticed you made the change. Thanks.

If you wouldn't mind squashing the commits, that would be beautiful and then I'll hit merge.

**Comment by Doomas** [comment]
Sorry, my bad.  Here you go.

**Comment by tilgovi** [comment]
Thanks so much!

**Pull request merged**
