### PR TITLE
Updated to support newer versions of Pyramid and OAuthLib

### PR DESCRIPTION
**Pull request by mmanderson**
* Removed dependency on pyramid.compat which has been deprecated in Pyramid
* Added code_challenge to OAUTH_PARAMS as it is now expected on a request even if it is None
* Updated test to handle new sorting of token types
* Updated setup.py requirements to newer versions of OAuthLib
* Updated tox.ini to remove unsupported python versions in testing

### CODE REVIEW

**Review by tilgovi — COMMENTED** [review]
This looks great! Thank you.

Let's change your comment slightly though. It'll be confusing, looking back in the future, to say that something changed upstream (when? how?).

Since there are no constants for this and it's basically internals, I think it's okay to just let this be 6 without explanations. Upstream has no explanations for their numbers.

Either that or subclass the standard bearer token class in the test suite so we can be explicit and robust about choosing an order.

I would import BearerToken as _BearerToken and define BeaterToken with an overridden estimation. I think that's a good example for users anyway, maybe. What do you think?

**Comment by mmanderson** [comment]
I took the easy route :-). If you would like, I could do the other. Thanks!

**Comment by tilgovi** [comment]
:-) looks great. Thanks.

**Comment by mmanderson** [comment]
Is there anything else that I need to do to have you merge this and release it?

**Comment by tilgovi** [comment]
I should be able to do this later today. I happen to be bouncing around a lot this week and haven't had any personal, non-employment time at the screen.

**Comment by mmanderson** [comment]
No problem. I understand about work getting in the way of . . . work :-D . Just wanted to make sure there wasn't anything else you needed from me. Thanks for making a great library!

**Comment by tilgovi** [comment]
Version 1.0.0 is released. Thanks for your help!

**Pull request merged**
